deployment:
  tasks:
    # Définir le chemin de déploiement
    - export DEPLOYPATH=/home/luso8827/planetapax/

    # Copier les fichiers de l'app
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH

    #Copier les dossiers de l'app
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
