deployment:
  tasks:
    # Define the deployment path
    - export DEPLOYPATH=/home/luso8827/planetapax/

    # Copy app's files
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH

    # Copy app's folders
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
